### ISSUE TITLE
Task: complete packaging and modularization

### ISSUE THREAD

**Issue by gkiar** [childmindresearch/survey_subsampling#3]
### Description

This was originally developed in a notebook, and the code shows it. We need to refactor in order to make it more sustainable and flexible moving forward.

### Tasks

- [x] Decouple assessment instruments from the main runscript
- [x] Decouple diagnostic targets from the from the main runscript
- [x] Decouple dataclass from runtime logic
- [x] Separate plotting code from processing code
- [ ] Add progress-bar to long-running stages (e.g., degraded learning)
- [ ] Add ability to stratify by additional axes of the dataset (e.g., subject ID)
- [x] Ensure consistent typing of inputs and outputs

**Comment by gkiar** [comment]
For progress bar, consider [rich](https://github.com/Textualize/rich)
